# Generated by Django 3.2 on 2023-08-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('cni_number', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('person_number', models.IntegerField(null=True)),
                ('enter_date', models.CharField(max_length=30, null=True)),
                ('exit_date', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
